import type { ThemePreset, ThemePresetId } from "./types";

export const themePresets: Record<ThemePresetId, ThemePreset> = {
  woodshop: {
    id: "woodshop",
    name: "Woodshop",
    description: "Walnut, oak and brass. Kliper's own look.",
    palette: {
      background: "#e9e5df",
      surface: "#f6f3ee",
      text: "#1f1b18",
      muted: "#5a544e",
      border: "#d4cec5",
      ink: "#2b211a",
      onInk: "#efe8de",
    },
    accent: { default: "#c8955a" },
    fonts: ["Outfit", "Oswald", "Playfair Display"],
    textures: ["wood-grain", "concrete", "none"],
    radius: { min: 0.75, max: 2.5, default: 2 },
  },
  "concrete-loft": {
    id: "concrete-loft",
    name: "Concrete Loft",
    description: "Raw grey, black type, one safety-orange hit.",
    palette: {
      background: "#cfcbc4",
      surface: "#e6e3de",
      text: "#141414",
      muted: "#4a4845",
      border: "#a9a49c",
      ink: "#141414",
      onInk: "#ecebe8",
    },
    accent: { default: "#e8622c" },
    fonts: ["Oswald", "Outfit", "Space Mono"],
    textures: ["concrete", "none"],
    radius: { min: 0, max: 1.5, default: 0.5 },
  },
  "classic-pole": {
    id: "classic-pole",
    name: "Classic Pole",
    description: "Cream, barber-pole red and navy.",
    palette: {
      background: "#f4efe4",
      surface: "#fffaf0",
      text: "#1e2a3a",
      muted: "#4f5a68",
      border: "#dccfb8",
      ink: "#1e3a5f",
      onInk: "#f4efe4",
    },
    accent: { default: "#b3261e" },
    fonts: ["Playfair Display", "Oswald", "Outfit"],
    textures: ["pole-stripes", "paper-grain", "none"],
    radius: { min: 0.25, max: 2, default: 1 },
  },
  "gentlemans-club": {
    id: "gentlemans-club",
    name: "Gentleman's Club",
    description: "Forest green, brass and leather, with serif type.",
    palette: {
      background: "#1f3a2e",
      surface: "#27463a",
      text: "#f1ead8",
      muted: "#c9c0a8",
      border: "#3f5d4f",
      ink: "#5c3a24",
      onInk: "#f1ead8",
    },
    accent: { default: "#b8893b" },
    fonts: ["Playfair Display", "Outfit"],
    textures: ["paper-grain", "none"],
    radius: { min: 0, max: 1.5, default: 0.75 },
  },
  "neon-fade": {
    id: "neon-fade",
    name: "Neon Fade",
    description: "Night-shop black with neon signage.",
    palette: {
      background: "#121215",
      surface: "#1c1c22",
      text: "#f2f2f5",
      muted: "#a9a9b6",
      border: "#2f2f3a",
      ink: "#0a0a0c",
      onInk: "#f2f2f5",
    },
    accent: { default: "#e040a0" },
    fonts: ["Righteous", "Bebas Neue", "Outfit"],
    textures: ["scanlines", "none"],
    radius: { min: 0.5, max: 2.5, default: 1.5 },
  },
  kanto: {
    id: "kanto",
    name: "Kanto",
    description: "Hand-painted signs in jeepney colors.",
    palette: {
      background: "#f2c230",
      surface: "#fff6d6",
      text: "#1b1b1b",
      muted: "#4b4430",
      border: "#1b1b1b",
      ink: "#1d4fa0",
      onInk: "#fff6d6",
    },
    accent: { default: "#c8102e" },
    fonts: ["Bebas Neue", "Righteous", "Oswald"],
    textures: ["halftone", "none"],
    radius: { min: 0, max: 1.5, default: 0.5 },
  },
  "clean-studio": {
    id: "clean-studio",
    name: "Clean Studio",
    description: "White, black and nothing extra.",
    palette: {
      background: "#f4f4f1",
      surface: "#fafaf7",
      text: "#1a1a1a",
      muted: "#5f5f5c",
      border: "#e1e1dc",
      ink: "#1a1a1a",
      onInk: "#fafaf7",
    },
    accent: { default: "#1a1a1a" },
    fonts: ["Outfit", "Space Mono"],
    textures: ["none"],
    radius: { min: 0, max: 2.5, default: 1.5 },
  },
  "retro-pomade": {
    id: "retro-pomade",
    name: "Retro Pomade",
    description: "Mint, cream and cherry red, straight from the 1950s.",
    palette: {
      background: "#bfe3d0",
      surface: "#f5eedc",
      text: "#2a2522",
      muted: "#5b524b",
      border: "#9fcab4",
      ink: "#2a2522",
      onInk: "#f5eedc",
    },
    accent: { default: "#c0392b" },
    fonts: ["Righteous", "Playfair Display", "Outfit"],
    textures: ["paper-grain", "pole-stripes", "none"],
    radius: { min: 0.5, max: 2.5, default: 1.5 },
  },
};
